// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TobaccoApi.Ef.Entities.Config;

namespace TobaccoApi.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20220412000456_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TobaccoApi.Ef.Entities.LeafDetail", b =>
                {
                    b.Property<int>("LeafDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CCT")
                        .HasColumnType("float");

                    b.Property<int>("LeafId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeafDetailId");

                    b.HasIndex("LeafId");

                    b.ToTable("LeafDetails");
                });

            modelBuilder.Entity("TobaccoApi.Entities.Leaf", b =>
                {
                    b.Property<int>("LeafId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeafId");

                    b.ToTable("Leafs");
                });

            modelBuilder.Entity("TobaccoApi.Ef.Entities.LeafDetail", b =>
                {
                    b.HasOne("TobaccoApi.Entities.Leaf", null)
                        .WithMany("LeafDetails")
                        .HasForeignKey("LeafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TobaccoApi.Entities.Leaf", b =>
                {
                    b.Navigation("LeafDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
